# Generated by Django 3.0.3 on 2020-07-13 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=200)),
                ('Article_slug', models.CharField(max_length=300)),
                ('Article_content', models.TextField()),
                ('Article_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Article_published', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 20, 39, 1, 401408), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
