# Generated by Django 3.0.3 on 2020-07-13 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200713_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 20, 55, 37, 902329), verbose_name='date published'),
        ),
    ]
