# Generated by Django 2.2 on 2020-07-13 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200713_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 58, 26, 875644), verbose_name='date published'),
        ),
    ]
