# Generated by Django 3.0.3 on 2020-07-14 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200713_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_content',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_image',
            new_name='article_image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_slug',
            new_name='article_slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_title',
            new_name='article_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Article_published',
        ),
        migrations.AddField(
            model_name='article',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 16, 31, 20, 90765), verbose_name='date published'),
        ),
    ]
